version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks: [appnet]

  backend:
    image: your-dockerhub-username/redis-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks: [appnet]

  frontend:
    image: your-dockerhub-username/redis-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    networks: [appnet]

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks: [appnet]

volumes:
  redis_data:
networks:
  appnet:

