version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks: [appnet]

  backend:
    image: devdoesdevops/redis-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks: [appnet]

  frontend:
    image: devdoesdevops/redis-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks: [appnet]

volumes:
  redis_data:
networks:
  appnet:

