version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks: [appnet]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks: [appnet]

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks: [appnet] 
volumes:
  redis_data:
networks:
  appnet:
