name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- CI: Install & Test ---
      - name: Install backend deps
        run: |
          cd backend
          npm install
          npm test || echo "no tests yet"

      - name: Install frontend deps
        run: |
          cd frontend
          npm install
          npm run build

      # --- Build & Push Docker Images ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/redis-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/redis-frontend:latest

      # --- Deploy on Azure VM ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/***
            if [ ! -d "redis-website" ]; then
              git clone https://github.com/dev-shelke/containerized-redis-joke-app.git
            fi
            cd containerized-redis-joke-app
            git pull origin master
            # run build/start commands here
            docker compose up -d --build
